travis:
  secure:
    BINSTAR_TOKEN: k50qPMvLOOdkSZ/xCOv5V/03fhx6ixCq+Kjtp18B8t9AIQDR4Md3k0J6YQflQdzleunvnBLMr4+hl6durj+Wntn7RVSheVMN6D1w3gKfAJQ7QhJBUIuVFaNtJxM2ezePDhRdqBBNS+jvn8QuyTa/6M4mHeDZKimT5onC4GO3RnNgeSoE5jHfRBi2Ac26FhU/lJLuMO0IV+VQx1TTHTOT4dTGkQhvLiTMj1HGHs0AhgoUZdmVxbDwVLh9dwlzTibp2hD+mkZN0o6C4xk45zU/YuUhCjMcBnxxW20QfUjGNh0Cye/GxSy1sPDMh/c7j7lKzD4fn3BiaPz7v7zv0L7ziXWTers/jEl6oo1A9xHTrcjqkZUU63Q9a9KIqripU4YtrrVWiW3sXW1ZFUovZ/4U1xx70E9BxE7P0U6gCjEd526JJDp//mJYjspV25H1ctBlUwcidcgvq2Lebg0BhTbj+toj2Z2YN7vEj3aCVERdp68t0HJEsFOriJXwsDXoJKbk5s0bVlbdb5FAPWxfKR9NgYmpYDE/vIIJ3N9ZtQ69in+Bjq/gt7T1EoyXG5Mrn88Rgo3Ac38+ge7q3bX3RDpshVJt3VvCpNF3Ee56sl4iVAy+Z+udoeJv1UEdHL//XPL9CYjsZ7GiTDyiOtwttqEi51wI1188UWuh5P3+a2DfOLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
