travis:
  secure:
    BINSTAR_TOKEN: mbJOsSWtPV9X7s9V+JO1TKPnagbwpXf3QCV9lm3Hhb7JqtCvPu90iakcaqs40f8o7KcqgElfV+pnjzjLfIV8k5qD/2wjsIFTYvNCjv1aVk3McTh5c/SRecn5UY6iQnS+v+26k/Fm0JKGGsFO3L+SioZcyuklEmo3uVTyMrcGE4mlAMSeqouun4DLUXBS8fzPCfzDzWqq/stckyocdz0LR3bh/JrfpER5PGZkQSqY1eihOLwOQu0z0Udg++8iPAty1Z8GAQ/SPzGCSwToKQ2fNPwG8w6ULu2G+3N5boKgGZLeoXXNji8uIMWT+8BmbkRFsBWVPL/hL+UeN6mH7T7mYSBFW19AlDurQPTFcEvJcacJxhackcT2jW0v6AyKCtJ8ouAnuGWNuTOooMBL/Bm/j1YhRshOZUwb7ol/FM1ke3XnrNq3ZWRUOVsfsYPrCFaThrhmzqK1ly2X6wkrU5afkGlaIkfIsth37bDdVacyOwFamkb2bFKz9V2gsH0GRrKlEC6YMBVKNeFMYJAoJDNInDkIBnxhxexeqjOwLV77+wkNhDl3jxOgFdyR+rrsNZH1mAcrQc/UtehbP7o3Q24kLX/Sucq1lPt1+kVeBwMKyCcsWCFTcSP3y2YLiSj6X8Y0yeLEFcex0m4PWCSpK82D4HLIjXhMgRQrhQcK1GftaIo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
